# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/storsimple8000series/

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/storsimple8000series/

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: storsimple8000series
    ArtifactName: packages
    Artifacts:
    - name: Azure.ResourceManager.Storsimple8000series
      safeName: AzureResourceManagerStorsimple8000series
