# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/hybriddatamanager/

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/hybriddatamanager/

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: hybriddatamanager
    ArtifactName: packages
    Artifacts:
    - name: Azure.ResourceManager.Hybriddatamanager
      safeName: AzureResourceManagerHybriddatamanager
